# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0002_auto_20170211_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhouseholdlogentry',
            name='next_appt_datetime_source',
            field=models.CharField(blank=True, choices=[('neighbour', 'Neighbour'), ('household member', 'Household Member'), ('hbc', 'Field RA'), ('OTHER', 'Other')], help_text='source of information for the appointment date', max_length=25, null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='householdlogentry',
            name='next_appt_datetime_source',
            field=models.CharField(blank=True, choices=[('neighbour', 'Neighbour'), ('household member', 'Household Member'), ('hbc', 'Field RA'), ('OTHER', 'Other')], help_text='source of information for the appointment date', max_length=25, null=True, verbose_name='Source'),
        ),
    ]
